/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamesstore;

import bd.DatabaseUtilit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author s2it_ggomes
 */
public class JFrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrmMenu
     */
    public JFrmMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        try {
            DatabaseUtilit.Conectar();
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "não foi possivel conectar...");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOptionSell = new javax.swing.JMenu();
        jMenuOptionClient = new javax.swing.JMenu();
        jMenuOptionSeller = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenuOptionSell.setText("Sell");
        jMenuOptionSell.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuOptionSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuOptionSellMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuOptionSell);

        jMenuOptionClient.setText("Client");
        jMenuOptionClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuOptionClientMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuOptionClient);

        jMenuOptionSeller.setText("Seller");
        jMenuOptionSeller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuOptionSellerMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuOptionSeller);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 937, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuOptionSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuOptionSellMouseClicked
        JFrmSell sell = new JFrmSell();
        sell.setVisible(true);
    }//GEN-LAST:event_jMenuOptionSellMouseClicked

    private void jMenuOptionClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuOptionClientMouseClicked
        JFrmClient client = new JFrmClient();
        client.setVisible(true);
    }//GEN-LAST:event_jMenuOptionClientMouseClicked

    private void jMenuOptionSellerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuOptionSellerMouseClicked
        JFrmSeller seller = new JFrmSeller();
        seller.setVisible(true);
    }//GEN-LAST:event_jMenuOptionSellerMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       DatabaseUtilit.Desconectar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuOptionClient;
    private javax.swing.JMenu jMenuOptionSell;
    private javax.swing.JMenu jMenuOptionSeller;
    // End of variables declaration//GEN-END:variables
}
